---  
title: | 
    | ICE development - Study 1 - data analysis -
    | `r params$factors` factors solution
author: "Małgorzata Wierzba, Jan Szczypiński, Dominika Zaremba, Michalina Marczak"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
editor_options: 
  chunk_output_type: console
params:
  factors: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.kable.NA = '')

library(knitr)
library(dplyr)
library(psych)
library(EFA.dimensions)
library(stringr)
```

```{r include=FALSE}
source('./S1/01-quality-control.R')
source('./S1/02-preprocessing.R')
```

```{r child = "S1/03-EFA.Rmd"}

```

```{r child = 'S1/04-reliability.Rmd'}

```

```{r child = if (params$factors == 7) 'S1/05-questionnaire.Rmd'}

```

## Note

This HTML output presents the general logic of the analysis along with some results not outlined in the main body of the manuscript. Please note that the full R code for the data cleaning and data analysis is available in the supplementary materials on the accompanying OSF website.
